source 'https://rubygems.org'

ruby '3.2.0'

# Rails framework
gem 'rails', '~> 7.0.0'
gem 'puma', '~> 5.0'

# Database
gem 'sqlite3', '~> 1.4'
gem 'pg', '~> 1.1'

# Authentication & Authorization
gem 'devise', '~> 4.8'
gem 'cancancan', '~> 3.2'

# API
gem 'jbuilder', '~> 2.11'
gem 'rack-cors'

# Background jobs
gem 'sidekiq', '~> 6.5'
gem 'redis', '~> 4.5'

# File uploads
gem 'carrierwave', '~> 2.2'
gem 'mini_magick', '~> 4.11'

# Utilities
gem 'bcrypt', '~> 3.1'
gem 'faker', '~> 2.20'
gem 'kaminari', '~> 1.2'

# Development & Test
group :development, :test do
  gem 'rspec-rails', '~> 5.1'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 2.20'
  gem 'pry-rails', '~> 0.3'
  gem 'pry-byebug', '~> 3.9'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring', '~> 4.0'
  gem 'web-console', '~> 4.1'
  gem 'bullet', '~> 6.2'
end

group :test do
  gem 'capybara', '~> 3.35'
  gem 'selenium-webdriver', '~> 4.1'
  gem 'webdrivers', '~> 5.0'
end 